name: $(BuildDefinitionName)-$(Date:yyyyMMdd).$(Rev:.r)

trigger:
- master

resources:
  repositories:
    - repository: templates
      type: git
      name: pipeline-templates

stages:
  - template: stages/build.yml@templates
  - template: stages/release.yml@templates