name: $(BuildDefinitionName)-$(Date:yyyyMMdd).$(Rev:.r)

trigger:
- master

resources:
  repositories:
    - repository: templates
      type: github
      name: microsoft-d365-ce-pfe-devops/D365-CE-Pipelines
      ref: refs/tags/blog-part-2.0
      endpoint: pipeline-templates

stages:
  - template: stages/build.yml@templates
  - template: stages/release.yml@templates